

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ERROR_NOTIFICATION_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ERROR_NOTIFICATION_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceErrorNotificationCallbackMethod0)(uint64_t uniffi_handle, RustBuffer notification, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceErrorNotificationCallbackMethod0(
				UniffiCallbackInterfaceErrorNotificationCallbackMethod0 cb, uint64_t uniffi_handle, RustBuffer notification, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, notification, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ERROR_NOTIFICATION_CALLBACK_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ERROR_NOTIFICATION_CALLBACK_METHOD1
typedef void (*UniffiCallbackInterfaceErrorNotificationCallbackMethod1)(uint64_t uniffi_handle, RustBuffer reason, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceErrorNotificationCallbackMethod1(
				UniffiCallbackInterfaceErrorNotificationCallbackMethod1 cb, uint64_t uniffi_handle, RustBuffer reason, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, reason, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOG_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOG_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceLogCallbackMethod0)(uint64_t uniffi_handle, RustBuffer log_level, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLogCallbackMethod0(
				UniffiCallbackInterfaceLogCallbackMethod0 cb, uint64_t uniffi_handle, RustBuffer log_level, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, log_level, message, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROTECT_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROTECT_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceProtectCallbackMethod0)(uint64_t uniffi_handle, int32_t socket_fd, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceProtectCallbackMethod0(
				UniffiCallbackInterfaceProtectCallbackMethod0 cb, uint64_t uniffi_handle, int32_t socket_fd, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, socket_fd, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ERROR_NOTIFICATION_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ERROR_NOTIFICATION_CALLBACK
typedef struct UniffiVTableCallbackInterfaceErrorNotificationCallback {
    UniffiCallbackInterfaceErrorNotificationCallbackMethod0 notify;
    UniffiCallbackInterfaceErrorNotificationCallbackMethod1 disconnected;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceErrorNotificationCallback;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOG_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOG_CALLBACK
typedef struct UniffiVTableCallbackInterfaceLogCallback {
    UniffiCallbackInterfaceLogCallbackMethod0 log;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceLogCallback;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROTECT_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROTECT_CALLBACK
typedef struct UniffiVTableCallbackInterfaceProtectCallback {
    UniffiCallbackInterfaceProtectCallbackMethod0 protect;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceProtectCallback;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_CLONE_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_CLONE_CONFIG
void* uniffi_ens_fn_clone_config(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FREE_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FREE_CONFIG
void uniffi_ens_fn_free_config(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_CONSTRUCTOR_CONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_CONSTRUCTOR_CONFIG_NEW
void* uniffi_ens_fn_constructor_config_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_ALLOW_ONLY_PQ
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_ALLOW_ONLY_PQ
void uniffi_ens_fn_method_config_set_allow_only_pq(void* ptr, int8_t allow_only_pq, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_BACKOFF_INITIAL
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_BACKOFF_INITIAL
void uniffi_ens_fn_method_config_set_backoff_initial(void* ptr, uint32_t seconds, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_BACKOFF_MAXIMAL
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_BACKOFF_MAXIMAL
void uniffi_ens_fn_method_config_set_backoff_maximal(void* ptr, RustBuffer seconds, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_BUFFER_SIZE
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_BUFFER_SIZE
void uniffi_ens_fn_method_config_set_buffer_size(void* ptr, uint32_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_KEEPALIVE_INTERVAL
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_KEEPALIVE_INTERVAL
void uniffi_ens_fn_method_config_set_keepalive_interval(void* ptr, RustBuffer seconds, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_KEEPALIVE_TIMEOUT
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_KEEPALIVE_TIMEOUT
void uniffi_ens_fn_method_config_set_keepalive_timeout(void* ptr, RustBuffer seconds, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_ROOT_CERTIFICATE_OVERRIDE
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONFIG_SET_ROOT_CERTIFICATE_OVERRIDE
void uniffi_ens_fn_method_config_set_root_certificate_override(void* ptr, RustBuffer override, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_CLONE_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_CLONE_CONNECTION
void* uniffi_ens_fn_clone_connection(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FREE_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FREE_CONNECTION
void uniffi_ens_fn_free_connection(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONNECTION_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_METHOD_CONNECTION_SHUTDOWN
void uniffi_ens_fn_method_connection_shutdown(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_INIT_CALLBACK_VTABLE_ERRORNOTIFICATIONCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_INIT_CALLBACK_VTABLE_ERRORNOTIFICATIONCALLBACK
void uniffi_ens_fn_init_callback_vtable_errornotificationcallback(UniffiVTableCallbackInterfaceErrorNotificationCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_INIT_CALLBACK_VTABLE_LOGCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_INIT_CALLBACK_VTABLE_LOGCALLBACK
void uniffi_ens_fn_init_callback_vtable_logcallback(UniffiVTableCallbackInterfaceLogCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_INIT_CALLBACK_VTABLE_PROTECTCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_INIT_CALLBACK_VTABLE_PROTECTCALLBACK
void uniffi_ens_fn_init_callback_vtable_protectcallback(UniffiVTableCallbackInterfaceProtectCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_CONNECT
void* uniffi_ens_fn_func_connect(RustBuffer socket_addr, RustBuffer protect_callback, RustBuffer authentication, uint64_t notification_callback, void* config, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_DEINIT
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_DEINIT
void uniffi_ens_fn_func_deinit(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_GET_MEMORY_USAGE
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_GET_MEMORY_USAGE
uint64_t uniffi_ens_fn_func_get_memory_usage(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_GET_VERSION
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_GET_VERSION
RustBuffer uniffi_ens_fn_func_get_version(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_INIT
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_INIT
void uniffi_ens_fn_func_init(RustBuffer app_version, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_SET_LOG_CALLBACK
#define UNIFFI_FFIDEF_UNIFFI_ENS_FN_FUNC_SET_LOG_CALLBACK
void uniffi_ens_fn_func_set_log_callback(RustBuffer max_level, uint64_t callback, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_ALLOC
RustBuffer ffi_ens_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_ens_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_FREE
void ffi_ens_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_ENS_RUSTBUFFER_RESERVE
RustBuffer ffi_ens_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U8
void ffi_ens_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U8
void ffi_ens_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U8
void ffi_ens_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_ens_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I8
void ffi_ens_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I8
void ffi_ens_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I8
void ffi_ens_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I8
int8_t ffi_ens_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U16
void ffi_ens_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U16
void ffi_ens_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U16
void ffi_ens_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_ens_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I16
void ffi_ens_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I16
void ffi_ens_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I16
void ffi_ens_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I16
int16_t ffi_ens_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U32
void ffi_ens_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U32
void ffi_ens_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U32
void ffi_ens_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_ens_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I32
void ffi_ens_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I32
void ffi_ens_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I32
void ffi_ens_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I32
int32_t ffi_ens_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_U64
void ffi_ens_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_U64
void ffi_ens_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_U64
void ffi_ens_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_ens_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_I64
void ffi_ens_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_I64
void ffi_ens_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_I64
void ffi_ens_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_I64
int64_t ffi_ens_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_F32
void ffi_ens_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_F32
void ffi_ens_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_F32
void ffi_ens_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_F32
float ffi_ens_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_F64
void ffi_ens_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_F64
void ffi_ens_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_F64
void ffi_ens_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_F64
double ffi_ens_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_POINTER
void ffi_ens_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_POINTER
void ffi_ens_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_POINTER
void ffi_ens_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_POINTER
void* ffi_ens_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_ens_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_ens_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_ens_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_ens_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_POLL_VOID
void ffi_ens_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_CANCEL_VOID
void ffi_ens_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_FREE_VOID
void ffi_ens_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_ENS_RUST_FUTURE_COMPLETE_VOID
void ffi_ens_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_CONNECT
uint16_t uniffi_ens_checksum_func_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_DEINIT
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_DEINIT
uint16_t uniffi_ens_checksum_func_deinit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_GET_MEMORY_USAGE
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_GET_MEMORY_USAGE
uint16_t uniffi_ens_checksum_func_get_memory_usage(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_GET_VERSION
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_GET_VERSION
uint16_t uniffi_ens_checksum_func_get_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_INIT
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_INIT
uint16_t uniffi_ens_checksum_func_init(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_SET_LOG_CALLBACK
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_FUNC_SET_LOG_CALLBACK
uint16_t uniffi_ens_checksum_func_set_log_callback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_ALLOW_ONLY_PQ
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_ALLOW_ONLY_PQ
uint16_t uniffi_ens_checksum_method_config_set_allow_only_pq(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_BACKOFF_INITIAL
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_BACKOFF_INITIAL
uint16_t uniffi_ens_checksum_method_config_set_backoff_initial(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_BACKOFF_MAXIMAL
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_BACKOFF_MAXIMAL
uint16_t uniffi_ens_checksum_method_config_set_backoff_maximal(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_BUFFER_SIZE
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_BUFFER_SIZE
uint16_t uniffi_ens_checksum_method_config_set_buffer_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_KEEPALIVE_INTERVAL
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_KEEPALIVE_INTERVAL
uint16_t uniffi_ens_checksum_method_config_set_keepalive_interval(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_KEEPALIVE_TIMEOUT
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_KEEPALIVE_TIMEOUT
uint16_t uniffi_ens_checksum_method_config_set_keepalive_timeout(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_ROOT_CERTIFICATE_OVERRIDE
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONFIG_SET_ROOT_CERTIFICATE_OVERRIDE
uint16_t uniffi_ens_checksum_method_config_set_root_certificate_override(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONNECTION_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_CONNECTION_SHUTDOWN
uint16_t uniffi_ens_checksum_method_connection_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_CONSTRUCTOR_CONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_CONSTRUCTOR_CONFIG_NEW
uint16_t uniffi_ens_checksum_constructor_config_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_ERRORNOTIFICATIONCALLBACK_NOTIFY
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_ERRORNOTIFICATIONCALLBACK_NOTIFY
uint16_t uniffi_ens_checksum_method_errornotificationcallback_notify(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_ERRORNOTIFICATIONCALLBACK_DISCONNECTED
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_ERRORNOTIFICATIONCALLBACK_DISCONNECTED
uint16_t uniffi_ens_checksum_method_errornotificationcallback_disconnected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_LOGCALLBACK_LOG
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_LOGCALLBACK_LOG
uint16_t uniffi_ens_checksum_method_logcallback_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_PROTECTCALLBACK_PROTECT
#define UNIFFI_FFIDEF_UNIFFI_ENS_CHECKSUM_METHOD_PROTECTCALLBACK_PROTECT
uint16_t uniffi_ens_checksum_method_protectcallback_protect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ENS_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_ENS_UNIFFI_CONTRACT_VERSION
uint32_t ffi_ens_uniffi_contract_version(void
    
);
#endif

 void ens_cgo_dispatchCallbackInterfaceErrorNotificationCallbackMethod0(uint64_t uniffi_handle, RustBuffer notification, void* uniffi_out_return, RustCallStatus* callStatus );
 void ens_cgo_dispatchCallbackInterfaceErrorNotificationCallbackMethod1(uint64_t uniffi_handle, RustBuffer reason, void* uniffi_out_return, RustCallStatus* callStatus );
 void ens_cgo_dispatchCallbackInterfaceErrorNotificationCallbackFree(uint64_t handle);
 void ens_cgo_dispatchCallbackInterfaceLogCallbackMethod0(uint64_t uniffi_handle, RustBuffer log_level, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );
 void ens_cgo_dispatchCallbackInterfaceLogCallbackFree(uint64_t handle);
 void ens_cgo_dispatchCallbackInterfaceProtectCallbackMethod0(uint64_t uniffi_handle, int32_t socket_fd, void* uniffi_out_return, RustCallStatus* callStatus );
 void ens_cgo_dispatchCallbackInterfaceProtectCallbackFree(uint64_t handle);
